server:
  port: 8013

spring:
  application:
    name: spring-cloud-sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 114.214.219.193:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://spring-cloud-sentinel-old-user-service
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://spring-cloud-sentinel-old-order-service
          predicates:
            - Path=/order/**
