server:
  port: 8091

spring:
  application:
    name: spring-cloud-consul-order-service
  datasource:
    username: root
    password: pvkYQN2yzVWZwGqcTzkb
    url: jdbc:mysql://114.214.219.193:3309/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: 192.168.124.5
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-02
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: 114.214.191.43
        health-check-interval: 10s

mybatis:
  type-aliases-package: com.olivine.order.domain
  mapper-locations:
    - classpath:mybatis/mapper/**Mapper.xml
